# Generated by Django 2.0.2 on 2018-02-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Song ID'),
        ),
    ]
