# Generated by Django 2.0.2 on 2018-02-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180222_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='song', verbose_name='커버 이미지'),
        ),
    ]
