# Generated by Django 2.0.2 on 2018-02-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_youtube_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='youtube_link',
            new_name='youtube_links',
        ),
    ]
