# Generated by Django 2.0.2 on 2018-02-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20180228_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistyoutube',
            name='url_thumbnail',
            field=models.URLField(blank=True, verbose_name='커버 이미지 URL'),
        ),
    ]
