# Generated by Django 2.0.2 on 2018-03-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_artistyoutube_url_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistyoutube',
            name='url_thumbnail',
            field=models.URLField(verbose_name='커버 이미지 URL'),
        ),
    ]
